#pragma once

enum SLOD_MARGIN_TYPE{

	SLOD_MARGIN_NONE,
	SLOD_MARGIN_LEFT_TOP_RIGHT_BOTTOM,
	SLOD_MARGIN_TOP,
	SLOD_MARGIN_BOTTOM,
	SLOD_MARGIN_LEFT,
	SLOD_MARGIN_RIGHT,
	SLOD_MARGIN_TOP_BOTTOM,
	SLOD_MARGIN_LEFT_RIGHT,
	SLOD_MARGIN_LEFT_TOP,
	SLOD_MARGIN_LEFT_BOTTOM,
	SLOD_MARGIN_RIGHT_BOTTOM,
	SLOD_MARGIN_TOP_RIGHT,
	SLOD_MARGIN_LEFT_TOP_RIGHT,
	SLOD_MARGIN_LEFT_RIGHT_BOTTOM, 
	SLOD_MARGIN_TOP_RIGHT_BOTTOM,
	SLOD_MARGIN_LEFT_TOP_BOTTOM,


};